### ISSUE TITLE
Configuration parameters

### ISSUE THREAD

**Issue by seunggookim** [creamlab/cleese#11]
I am trying to replicate some `'pitch'` transformations done with the MATLAB version and having difficulties replicating them.
I matched all other parameters, but I've noticed some parameters do not exist in the Python version:
```matlab
st_pars.svp.b_preserveTransients = 1;
st_pars.svp.b_normalizeOutput    = 1;
st_pars.pitch.b_preserveEnvelope = 1; 
```

Output Normalization can be easily done via RMS equalization, but it seems that the envelopes look different:
![image](https://user-images.githubusercontent.com/65642292/176925580-8e8a5d76-6263-49a7-9afe-f87229a24452.png)
Also, the phases look different:
![image](https://user-images.githubusercontent.com/65642292/176926350-8914f6c2-793b-4ffe-8236-cfeea2ca01a1.png)

Perhaps, are there any options to reduce this discrepancy?

**Comment by jjau** [comment]
Hello, 
These parameters (transient preservation, spectral envelope preservation) correspond to an old, deprecated version of cleese, which used the (closed source) SuperVP audio engine in MATLAB. These parameters are not currently implemented in the current python version, which uses a simpler but open-source implementation of the phase vocoder. Future versions could implement these two additional features, if needed, but this is not currently deemed a priority.
