### ISSUE TITLE
`run_cleese` fails with `ValueError`

### ISSUE THREAD

**Issue by logc** [creamlab/cleese#2]
There is no supplied `example.wav` in the repository. If one is created, then running `run_cleese.py` does not succeed.

```console
$ python run_cleese.py
stretch variation 1/10
Traceback (most recent call last):
  File "run_cleese.py", line 15, in <module>
    cleese.process(soundData=inputFile, configFile=configFile)
  File "/Users/luis/Documents/code/cleese/cleese/cleeseProcess.py", line 138, in process
    waveOut = processWithPV(waveIn=waveIn, pars=pars, BPF=BPF, doPitchShift=doPitchShift)
  File "/Users/luis/Documents/code/cleese/cleese/cleeseProcess.py", line 302, in processWithPV
    stftMat = stft(waveIn,win,n_fft,anaHopVec)
  File "/Users/luis/Documents/code/cleese/cleese/cleeseEngine.py", line 23, in stft
    waveForm = np.concatenate((waveForm,np.zeros(numExtraSamples)))
ValueError: all the input arrays must have same number of dimensions
```

**Comment by jjburred** [comment]
works here. Did you use a valid wav file? Anyway, will replace 'example.wav' in the code with a reference to one of the provided wav files for the tutorial

**Comment by logc** [comment]
I recorded an `aifc` file with Quicktime, then converted it with `ffmpeg -i ~/Desktop/example.aifc ./example.wav`. Not sure if that results in a valid WAV file ...

**Comment by jjburred** [comment]
could you send me over your wav file?

**Comment by jjburred** [comment]
ah yes, CLEESE does not handle stereo files. I'm committing a check and warning for stereo files, in which case only the left channel will be processed. thanks
